"""Writes the walkthrough's Rocketbox avatar catalog from build-rocketbox-library.sh's avatars.jsonl.

  python gen-rocketbox-catalog.py rocketbox-avatars.jsonl <rocketbox-catalog.ts>
"""

import json
import sys

src, dst = sys.argv[1:]
order = {'Adults': 0, 'Children': 1, 'Professions': 2}
rows = {}
for line in open(src):
    if line.strip():
        row = json.loads(line)
        known = rows.get(row['id'])
        # The two party outfits sit under both Adults and Professions: keep Adults.
        if known is None or order.get(row['group'], 9) <= order.get(known['group'], 9):
            rows[row['id']] = row
avatars = sorted(rows.values(), key=lambda r: (order.get(r['group'], 9), r['id']))
lines = [
    '// Generated by scripts/characters/gen-rocketbox-catalog.py from the built',
    '// Rocketbox avatars (rocketbox-avatars.jsonl): do not edit by hand.',
    '',
    "export type RocketboxGroup = 'Adults' | 'Children' | 'Professions'",
    '',
    '/** A Rocketbox avatar body and its hip height (m), which scales the shared clips to it. */',
    'export type RocketboxAvatar = { id: string; group: RocketboxGroup; hip: number }',
    '',
    'export const ROCKETBOX_AVATARS: readonly RocketboxAvatar[] = [',
]
lines += [f"  {{ id: '{r['id']}', group: '{r['group']}', hip: {r['hip']} }}," for r in avatars]
lines += [']', '']
open(dst, 'w').write('\n'.join(lines))
print(f'{len(avatars)} avatars -> {dst}')
