/**
 * Korean names for the paintable parts of furniture models. A model tags a
 * part with a `slot_<id>` material; the ids are English words, sometimes
 * joined with underscores (`bed_frame`).
 */
const PART_WORDS: Record<string, string> = {
  a: '부분 A',
  accent: '포인트',
  arm: '팔걸이',
  armrest: '팔걸이',
  arms: '팔걸이',
  back: '등받이',
  backboard: '백보드',
  backrest: '등받이',
  bag: '가방',
  bar: '봉',
  base: '받침',
  basin: '세면대',
  bed: '침대',
  blades: '날개',
  board: '판',
  body: '몸체',
  bowl: '그릇',
  b: '부분 B',
  bulb: '전구',
  buttons: '버튼',
  c: '부분 C',
  cabinet: '수납장',
  cable: '케이블',
  canopy: '캐노피',
  canvas: '캔버스',
  capsule: '캡슐',
  charger: '충전기',
  coconut: '코코넛',
  controls: '조작부',
  cooktop: '쿡탑',
  countertop: '조리대',
  cover: '커버',
  cups: '컵',
  cushion: '쿠션',
  cushions: '쿠션',
  detail: '장식',
  display: '화면',
  door: '문',
  doors: '문',
  drawer: '서랍',
  drawers: '서랍',
  driver: '드라이버',
  fabric: '패브릭',
  faucet: '수전',
  fixtures: '부속',
  flowers: '꽃',
  foliage: '잎',
  frame: '프레임',
  glass: '유리',
  grill: '그릴',
  ground: '바닥',
  handle: '손잡이',
  handles: '손잡이',
  hardware: '철물',
  head: '머리',
  headboard: '헤드보드',
  headrest: '머리받이',
  holder: '거치대',
  hoop: '링',
  inner: '안쪽',
  keys: '건반',
  keysblack: '검은 건반',
  keyswhite: '흰 건반',
  knob: '노브',
  knobs: '노브',
  label: '라벨',
  lamp: '램프',
  leather: '가죽',
  leaves: '잎',
  leg: '다리',
  legs: '다리',
  lid: '뚜껑',
  light: '조명',
  main: '본체',
  marking: '표시',
  matress: '매트리스',
  mattress: '매트리스',
  metal: '금속',
  mirror: '거울',
  motor: '모터',
  neck: '넥',
  needle: '바늘',
  outer: '바깥쪽',
  pan: '팬',
  panel: '패널',
  paper: '종이',
  pedal: '페달',
  pedals: '페달',
  petals: '꽃잎',
  picture: '그림',
  pillow: '베개',
  pillows: '베개',
  plate: '판',
  pole: '기둥',
  pot: '화분',
  rack: '거치대',
  rim: '테두리',
  roof: '지붕',
  screen: '화면',
  seat: '좌석',
  shade: '갓',
  sheet: '시트',
  shelf: '선반',
  shelves: '선반',
  sign: '표지',
  sink: '싱크',
  soil: '흙',
  soleplate: '바닥판',
  steering: '핸들',
  stem: '줄기',
  strings: '줄',
  structure: '구조',
  table: '테이블',
  top: '상판',
  toilet: '변기',
  trim: '테두리 장식',
  trunk: '줄기',
  tub: '욕조',
  utensils: '조리도구',
  vents: '통풍구',
  water: '물',
  weights: '원판',
  wheels: '바퀴',
  windows: '창',
  wood: '나무',
}

/** The part's Korean name, or null when a word of its id is unknown. */
export function furniturePartName(slotId: string): string | null {
  const words = slotId
    .toLowerCase()
    .split(/[_\s-]+/)
    .filter(Boolean)
  if (words.length === 0) return null
  const names = words.map((word) => PART_WORDS[word])
  return names.every(Boolean) ? names.join(' ') : null
}
