import type { EmoteId, FaceSliderGroup, FaceSliderId } from '@pascal-app/editor'
import {
  Angry,
  Brain,
  Camera,
  CircleHelp,
  Coffee,
  DoorClosed,
  Eye,
  Frown,
  Hand,
  HandMetal,
  Heart,
  Laugh,
  type LucideIcon,
  MessagesSquare,
  Moon,
  Music,
  Music2,
  Music3,
  Music4,
  PartyPopper,
  Presentation,
  Sparkles,
  ThumbsDown,
  ThumbsUp,
  Trophy,
} from 'lucide-react'

export type Swatch = { hex: string; name: string }

/** Hair dyes, natural shades first, then fashion colours. */
export const HAIR_SWATCHES: Swatch[] = [
  { hex: '#1B1918', name: '자연 흑발' },
  { hex: '#1D2433', name: '블루 블랙' },
  { hex: '#3A2A22', name: '흑갈색' },
  { hex: '#4F3426', name: '다크 브라운' },
  { hex: '#6B4331', name: '초코 브라운' },
  { hex: '#8A5F43', name: '밀크 브라운' },
  { hex: '#7A6A5E', name: '애쉬 브라운' },
  { hex: '#A06F3C', name: '골드 브라운' },
  { hex: '#A4532A', name: '오렌지 브라운' },
  { hex: '#C89B5D', name: '허니 블론드' },
  { hex: '#E3D3B0', name: '플래티넘' },
  { hex: '#9A9A98', name: '애쉬 그레이' },
  { hex: '#C9CBCF', name: '실버' },
  { hex: '#5E1F2A', name: '버건디' },
  { hex: '#8C2436', name: '와인 레드' },
  { hex: '#D88AA6', name: '핑크' },
  { hex: '#9D8AC7', name: '라벤더' },
  { hex: '#2A3A63', name: '네이비' },
  { hex: '#3F7FBF', name: '블루' },
  { hex: '#7FC4B0', name: '민트' },
]

/** Skin tones, fairest first. */
export const SKIN_SWATCHES: Swatch[] = [
  { hex: '#F3D9C8', name: '아주 밝은' },
  { hex: '#EDC9AE', name: '밝은 핑크' },
  { hex: '#EAC3A6', name: '밝은' },
  { hex: '#E2B38E', name: '밝은 웜' },
  { hex: '#D9A77F', name: '자연' },
  { hex: '#D4A07A', name: '웜 베이지' },
  { hex: '#C68D63', name: '허니' },
  { hex: '#B07650', name: '탠' },
  { hex: '#9A6240', name: '브론즈' },
  { hex: '#8A5638', name: '카라멜' },
  { hex: '#6E432B', name: '브라운' },
  { hex: '#553320', name: '딥 브라운' },
  { hex: '#3F2519', name: '에스프레소' },
]

export const EMOTE_ICONS: Record<EmoteId, LucideIcon> = {
  wave: Hand,
  waveBig: HandMetal,
  clap: Heart,
  cheer: PartyPopper,
  hooray: Trophy,
  nod: ThumbsUp,
  headShake: ThumbsDown,
  danceCool: Music,
  danceGroove: Music2,
  danceSilly: Music3,
  danceHard: Music4,
  laugh: Laugh,
  shrug: CircleHelp,
  think: Brain,
  angry: Angry,
  sad: Frown,
  yawn: Moon,
  present: Presentation,
  talk: MessagesSquare,
  stretch: Sparkles,
  lookAround: Eye,
  scratchHead: CircleHelp,
  photo: Camera,
  knock: DoorClosed,
  drink: Coffee,
}

export const FACE_GROUP_LABELS: Record<FaceSliderGroup, string> = {
  face: '얼굴형',
  eyes: '눈',
  brows: '눈썹',
  nose: '코',
  mouth: '입',
}

/** Each face slider's name, and what its two ends do. */
export const FACE_SLIDER_TEXT: Record<FaceSliderId, { label: string; low: string; high: string }> =
  {
    faceWidth: { label: '얼굴 너비', low: '좁게', high: '넓게' },
    faceLength: { label: '얼굴 길이', low: '짧게', high: '길게' },
    jawWidth: { label: '턱선 너비', low: '갸름하게', high: '각지게' },
    chinWidth: { label: '턱끝 너비', low: '뾰족하게', high: '넓게' },
    chinLength: { label: '턱끝 길이', low: '짧게', high: '길게' },
    chinDepth: { label: '턱끝 돌출', low: '들어가게', high: '나오게' },
    cheekbones: { label: '광대', low: '낮게', high: '도드라지게' },
    cheeks: { label: '볼살', low: '홀쭉하게', high: '통통하게' },
    forehead: { label: '이마', low: '평평하게', high: '볼록하게' },
    eyeSize: { label: '눈 크기', low: '작게', high: '크게' },
    eyeSpacing: { label: '눈 사이', low: '좁게', high: '넓게' },
    eyeHeight: { label: '눈 높이', low: '아래로', high: '위로' },
    eyeTilt: { label: '눈꼬리', low: '처지게', high: '올라가게' },
    eyeDepth: { label: '눈 깊이', low: '나오게', high: '깊게' },
    browHeight: { label: '눈썹 높이', low: '아래로', high: '위로' },
    browTilt: { label: '눈썹 꼬리', low: '처지게', high: '올라가게' },
    noseWidth: { label: '콧볼 너비', low: '좁게', high: '넓게' },
    noseLength: { label: '코 길이', low: '짧게', high: '길게' },
    noseHeight: { label: '콧대 높이', low: '낮게', high: '높게' },
    noseTip: { label: '코끝', low: '내려가게', high: '들리게' },
    mouthWidth: { label: '입 너비', low: '좁게', high: '넓게' },
    mouthHeight: { label: '입 위치', low: '아래로', high: '위로' },
    lipFullness: { label: '입술 두께', low: '얇게', high: '도톰하게' },
    mouthCorners: { label: '입꼬리', low: '내려가게', high: '올라가게' },
  }
