import type { EmoteId } from '@pascal-app/editor'
import {
  Angry,
  Brain,
  Camera,
  CircleHelp,
  Coffee,
  DoorClosed,
  Eye,
  Frown,
  Hand,
  HandMetal,
  Heart,
  Laugh,
  type LucideIcon,
  MessagesSquare,
  Moon,
  Music,
  Music2,
  Music3,
  Music4,
  PartyPopper,
  Presentation,
  Sparkles,
  ThumbsDown,
  ThumbsUp,
  Trophy,
} from 'lucide-react'

export type Swatch = { hex: string; name: string }

/** Hair dyes, natural shades first, then fashion colours. */
export const HAIR_SWATCHES: Swatch[] = [
  { hex: '#1B1918', name: '자연 흑발' },
  { hex: '#1D2433', name: '블루 블랙' },
  { hex: '#3A2A22', name: '흑갈색' },
  { hex: '#4F3426', name: '다크 브라운' },
  { hex: '#6B4331', name: '초코 브라운' },
  { hex: '#8A5F43', name: '밀크 브라운' },
  { hex: '#7A6A5E', name: '애쉬 브라운' },
  { hex: '#A06F3C', name: '골드 브라운' },
  { hex: '#A4532A', name: '오렌지 브라운' },
  { hex: '#C89B5D', name: '허니 블론드' },
  { hex: '#E3D3B0', name: '플래티넘' },
  { hex: '#9A9A98', name: '애쉬 그레이' },
  { hex: '#C9CBCF', name: '실버' },
  { hex: '#5E1F2A', name: '버건디' },
  { hex: '#8C2436', name: '와인 레드' },
  { hex: '#D88AA6', name: '핑크' },
  { hex: '#9D8AC7', name: '라벤더' },
  { hex: '#2A3A63', name: '네이비' },
  { hex: '#3F7FBF', name: '블루' },
  { hex: '#7FC4B0', name: '민트' },
]

/** Skin tones, fairest first. */
export const SKIN_SWATCHES: Swatch[] = [
  { hex: '#F3D9C8', name: '아주 밝은' },
  { hex: '#EDC9AE', name: '밝은 핑크' },
  { hex: '#EAC3A6', name: '밝은' },
  { hex: '#E2B38E', name: '밝은 웜' },
  { hex: '#D9A77F', name: '자연' },
  { hex: '#D4A07A', name: '웜 베이지' },
  { hex: '#C68D63', name: '허니' },
  { hex: '#B07650', name: '탠' },
  { hex: '#9A6240', name: '브론즈' },
  { hex: '#8A5638', name: '카라멜' },
  { hex: '#6E432B', name: '브라운' },
  { hex: '#553320', name: '딥 브라운' },
  { hex: '#3F2519', name: '에스프레소' },
]

export const EMOTE_ICONS: Record<EmoteId, LucideIcon> = {
  wave: Hand,
  waveBig: HandMetal,
  clap: Heart,
  cheer: PartyPopper,
  hooray: Trophy,
  nod: ThumbsUp,
  headShake: ThumbsDown,
  danceCool: Music,
  danceGroove: Music2,
  danceSilly: Music3,
  danceHard: Music4,
  laugh: Laugh,
  shrug: CircleHelp,
  think: Brain,
  angry: Angry,
  sad: Frown,
  yawn: Moon,
  present: Presentation,
  talk: MessagesSquare,
  stretch: Sparkles,
  lookAround: Eye,
  scratchHead: CircleHelp,
  photo: Camera,
  knock: DoorClosed,
  drink: Coffee,
}
