/** Korean display names for the built-in catalog, keyed by catalog id. */
export const CATALOG_KO_NAMES: Record<string, string> = {
  cactus: '선인장',
  'tv-stand': 'TV 거실장',
  'dining-table-mo9ms5yh': '원목 식탁',
  'single-bed': '싱글 침대',
  'livingroom-chair': '거실 의자',
  'small-indoor-plant': '작은 화분',
  column: '기둥',
  barbell: '바벨',
  toy: '장난감',
  'barbell-stand': '바벨 거치대',
  books: '책',
  stool: '스툴',
  'pool-table': '당구대',
  bookshelf: '책장',
  'coat-rack': '옷걸이 스탠드',
  'car-toy': '자동차 장난감',
  'bedside-table': '협탁',
  sofa: '소파',
  bunkbed: '2층 침대',
  'my-leather-couch-modp80ha': '가죽 카우치',
  'office-table': '사무용 책상',
  'dining-table': '식탁',
  guitar: '기타',
  'trash-bin': '휴지통',
  'recessed-light': '매입등',
  shelf: '선반',
  'table-lamp': '테이블 스탠드',
  'ceiling-lamp': '천장등',
  closet: '옷장',
  'coffee-table': '커피 테이블',
  'dining-chair': '식탁 의자',
  dresser: '서랍장',
  'ikea-kallax-1x4-moa2y49n': '칼락스 수납장 2x4',
  'indoor-plant': '실내 화분',
  'ironing-board': '다리미판',
  'double-bed': '더블 침대',
  'floor-lamp': '플로어 스탠드',
  'herman-miller-aeron-mo8x36k9': '허먼밀러 에어론',
  easel: '이젤',
  'lounge-chair': '라운지 체어',
  'office-chair': '사무용 의자',
  piano: '피아노',
  picture: '액자',
  'rectangular-carpet': '사각 러그',
  'round-mirror': '원형 거울',
  'round-carpet': '원형 러그',
  threadmill: '러닝머신',
  'standing-desk-mo8wgz95': '스탠딩 데스크',
  sprinkler: '스프링클러',
  'exit-sign': '비상구 표시등',
  'sewing-machine': '재봉틀',
  television: 'TV',
  'power-outlet-moa09g0o': '콘센트',
  'ac-block': '실외기',
  'stereo-speaker': '스피커',
  thermostat: '온도 조절기',
  toaster: '토스터',
  kettle: '전기 주전자',
  hydrant: '소화전',
  'fire-detector': '화재 감지기',
  'smoke-detector': '연기 감지기',
  'coffee-machine': '커피 머신',
  'ceiling-fan': '실링팬',
  iron: '다리미',
  'air-conditioning': '에어컨',
  computer: '컴퓨터',
  'alarm-keypad': '경보 키패드',
  'ev-wall-charger': '전기차 충전기',
  'electric-panel': '분전반',
  'bathroom-sink': '세면대',
  'shower-angle': '코너 샤워부스',
  'toilet-paper': '휴지걸이',
  'washing-machine': '세탁기',
  'shower-rug': '욕실 매트',
  bathtub: '욕조',
  'laundry-bag': '빨래 바구니',
  'shower-square': '사각 샤워부스',
  'drying-rack': '빨래 건조대',
  toilet: '양변기',
  microwave: '전자레인지',
  'cutting-board': '도마',
  'kitchen-utensils': '주방 도구',
  'kitchen-counter': '주방 조리대',
  hood: '레인지 후드',
  'wooden-kitchen-bar-moa2hhh4': '주방 바',
  'kitchen-cabinet': '주방 수납장',
  kitchen: '주방 세트',
  'frying-pan': '프라이팬',
  fruits: '과일',
  fridge: '냉장고',
  'kitchen-shelf': '주방 선반',
  'wine-bottle': '와인병',
  stove: '가스레인지',
  ball: '공',
  bush: '관목',
  'basket-hoop': '농구 골대',
  'parking-spot': '주차 구역',
  palm: '야자수',
  sunbed: '선베드',
  'fir-tree': '전나무',
  tree: '나무',
  skate: '스케이트보드',
  '1967-chevrolet-camaro-moa24wsf': '쉐보레 카마로 1967',
  'outdoor-playhouse': '야외 놀이집',
  'patio-umbrella': '파라솔',
  pillar: '기둥 (원형)',
  scooter: '킥보드',
  tesla: '테슬라 모델 Y',
  'dishwasher-movn72ls': '식기세척기',
  'fireplace-movn1fnn': '벽난로',
}
