/** Korean display names for the core material library, keyed by material id. */
export const MATERIAL_KO_NAMES: Record<string, string> = {
  'wood-finewood27': '고운 원목 27',
  'wood-floorplank1': '마루 판재 1',
  'wood-hungarianparquet10': '헤링본 마루 10',
  'wood-hungarianparquet2': '헤링본 마루 2',
  'wood-squareparquet21': '격자 마루 21',
  'wood-squareparquet23': '격자 마루 23',
  'wood-woodfine1': '원목 1',
  'wood-woodfine11': '원목 11',
  'wood-woodfine13': '원목 13',
  'wood-woodfine2': '원목 2',
  'wood-woodfine22': '원목 22',
  'wood-woodfine24': '원목 24',
  'wood-woodparquet14': '원목 마루 14',
  'wood-woodenparquet11': '원목 마루 11',
  'wood-woodparquet121': '원목 마루 121',
  'wood-woodparquet56': '원목 마루 56',
  'wood-woodparquet65': '원목 마루 65',
  'wood-woodparquet99': '원목 마루 99',
  'wood-woodplank19': '원목 판재 19',
  'wood-woodplank48': '원목 판재 48',
  'flooring-tile85a': '쿼리 타일',
  'flooring-rusticbrick': '러스틱 벽돌',
  'flooring-agedbrick': '고벽돌',
  'flooring-weatheredbrick': '풍화 벽돌',
  'flooring-garagedoor': '차고 패널',
  'flooring-greenlabradorite': '그린 라브라도라이트',
  'flooring-ground13': '흙바닥',
  'flooring-pooltiles': '수영장 타일',
  'flooring-tiles3': '체커 타일',
  'flooring-tiles4': '격자 타일',
  'flooring-wallstone1': '석재 벽',
  'flooring-woodenceramic3': '우드 세라믹 3',
  'flooring-ceramic53': '세라믹 모자이크',
  'flooring-terrazzo19': '테라조',
  'flooring-tile79': '석재 타일',
  'flooring-tile86': '테라코타 타일',
  'flooring-greenquartzitea': '그린 규암',
  'flooring-darkceramic22': '다크 세라믹',
  'flooring-lightceramic24': '라이트 세라믹',
  'flooring-statuarettowhite': '스타투아리오 화이트',
  'flooring-tile20': '모자이크 타일',
  'flooring-tile68': '패턴 타일',
  'flooring-woodenceramic2': '우드 세라믹 2',
  'flooring-woodparquet76': '원목 마루',
  'roof-classicshingles': '클래식 싱글',
  'roof-claytiles': '점토 기와',
  'roof-terracottatiles': '테라코타 기와',
  'roof-weatheredshingles': '풍화 싱글',
  'preset-white': '화이트',
  'preset-softwhite': '소프트 화이트',
  'preset-cream': '크림',
  'preset-beige': '베이지',
  'preset-lightgrey': '라이트 그레이',
  'preset-greige': '그레이지',
  'preset-midgrey': '미드 그레이',
  'preset-charcoal': '차콜',
  'preset-nearblack': '블랙',
  'preset-blush': '블러시',
  'preset-tomato': '토마토',
  'preset-brickred': '브릭 레드',
  'preset-oxblood': '옥스블러드',
  'preset-peach': '피치',
  'preset-terracotta': '테라코타',
  'preset-burntorange': '번트 오렌지',
  'preset-clay': '클레이',
  'preset-paleyellow': '페일 옐로',
  'preset-mustard': '머스터드',
  'preset-ochre': '오커',
  'preset-gold': '골드',
  'preset-mint': '민트',
  'preset-sage': '세이지',
  'preset-olive': '올리브',
  'preset-forest': '포레스트',
  'preset-paleteal': '페일 틸',
  'preset-teal': '틸',
  'preset-deepteal': '딥 틸',
  'preset-powderblue': '파우더 블루',
  'preset-softblue': '소프트 블루',
  'preset-sky': '스카이',
  'preset-slateblue': '슬레이트 블루',
  'preset-royalblue': '로열 블루',
  'preset-navy': '네이비',
  'preset-lavender': '라벤더',
  'preset-plum': '플럼',
  'preset-aubergine': '오베르진',
  'preset-petal': '페탈',
  'preset-rose': '로즈',
  'preset-dustyrose': '더스티 로즈',
  'preset-berry': '베리',
  'preset-sand': '샌드',
  'preset-tan': '탄',
  'preset-taupe': '토프',
  'preset-espresso': '에스프레소',
  'preset-metal': '금속',
  'preset-glass': '유리',
  'fabric-linen': '린넨',
  'fabric-cotton': '코튼',
  'fabric-velvet': '벨벳',
  'fabric-wool': '울',
  'fabric-suede': '스웨이드',
  'fabric-boucle': '부클레',
  'leather-black': '블랙 가죽',
  'leather-calf': '송아지 가죽',
  'concrete-plaster': '도장 미장',
  'concrete-polished': '폴리싱 콘크리트',
  'concrete-raw': '노출 콘크리트',
  'concrete-plate': '콘크리트 패널',
  'concrete-stucco': '화이트 스터코',
  'concrete-drywall': '석고보드',
  'metal-copper': '구리',
  'metal-polished': '광택 금속',
  'metal-steel': '헤어라인 스틸',
  'metal-brass': '황동',
  'metal-chrome': '크롬',
}

export function materialKoName(item: { id: string; label: string }): string {
  return MATERIAL_KO_NAMES[item.id] ?? item.label
}

/** Korean tab names for the material library categories. */
export const MATERIAL_CATEGORY_KO: Record<string, string> = {
  colors: '색상',
  wood: '목재',
  stone: '석재',
  brick: '벽돌',
  tile: '타일',
  concrete: '콘크리트',
  metal: '금속',
  fabric: '패브릭',
  leather: '가죽',
  roofing: '지붕재',
  ground: '바닥재',
  glass: '유리',
}
