'use client'

import { useEffect, useState } from 'react'
import { FACE_POINT_COUNT } from './face-points'

/**
 * Every Rocketbox character's face landmarks (FACE_POINT_INDICES, flattened
 * x/y fractions of the head's front view), found by MediaPipe on each head
 * as renderFront draws it: a face photo is warped onto them. Generated by
 * scripts/characters/gen-face-points.ts; regenerate it whenever the front
 * view's framing (head-geometry.ts) changes.
 */
const FACE_TARGETS_URL = '/characters/rocketbox/face-points.json'

type FaceTargets = Record<string, number[]>

let targets: Promise<FaceTargets> | null = null

/** The targets once downloaded, so a hook can give them at once. */
let loaded: FaceTargets | null = null

export function loadFaceTargets(): Promise<FaceTargets> {
  targets ??= fetch(FACE_TARGETS_URL)
    .then((response) => {
      if (!response.ok) throw new Error(`face points: ${response.status}`)
      return response.json() as Promise<{ count: number; avatars: FaceTargets }>
    })
    .then((file) => {
      if (file.count !== FACE_POINT_COUNT) throw new Error('face points: out of date')
      loaded = file.avatars
      return file.avatars
    })
    .catch((error: unknown) => {
      // A failed download can be tried again later.
      targets = null
      throw error
    })
  return targets
}

/**
 * A character's face landmarks (packed front-view points): undefined while
 * they load (or couldn't be), null when the character has none (its face is
 * covered). The same array for as long as the character stays.
 */
export function useFaceTarget(avatarId: string): readonly number[] | null | undefined {
  const [, setReady] = useState(loaded !== null)
  useEffect(() => {
    if (loaded) return
    let live = true
    loadFaceTargets().then(
      () => {
        if (live) setReady(true)
      },
      (error: unknown) => console.warn('[look] could not load the face landmarks', error),
    )
    return () => {
      live = false
    }
  }, [])
  return loaded ? (loaded[avatarId] ?? null) : undefined
}
