import { ALL_AVATARS, type AvatarGender } from './avatar-catalog'

/**
 * A hairstyle: null keeps the character's own; BALD takes its hair off
 * (see bald-head.ts); any other is the id of the avatar whose hair it
 * wears, over the bald head.
 */
export type HairStyle = string | null

export const BALD = 'bald'

const AVATAR_IDS = new Set(ALL_AVATARS.map((avatar) => avatar.id))

/** A hairstyle as saved or received: the character's own for anything unknown. */
export function readHairStyle(value: unknown): HairStyle {
  if (value === BALD) return BALD
  return typeof value === 'string' && AVATAR_IDS.has(value) ? value : null
}

/** A hairstyle the library offers: the avatar whose hair it is, and how that hair reads. */
export type HairStyleEntry = {
  id: string
  gender: AvatarGender
  length: 'short' | 'medium' | 'long'
}

/**
 * The bald skull every head shares (Rocketbox heads are one template per
 * sex), which hairstyles are carried over by: its points and their normals
 * (bind pose, in its own units: see head-skull.ts), each point's share of
 * hair (0 on the face and ears, 1 where nearly every character's hair
 * volume stands out of the skull), the face bones it is fitted to a
 * character by, and its triangles. The skull is one bald man's; the bald
 * surface closing a head (see bald-head.ts) is the cranium of the other
 * bald heads with its face bones, on its triangles: its points and their
 * normals `bald`, `baldNormals`.
 */
export type SkullData = {
  bones: Record<string, [number, number, number]>
  points: Float32Array
  normals: Float32Array
  zone: Float32Array
  triangles: Uint32Array
  bald: Float32Array
  baldNormals: Float32Array
}

/**
 * The skull as the file stores it, in whole numbers: points in POINT_UNIT,
 * normals in NORMAL_UNIT, zone shares in ZONE_UNIT (the bald cranium's as
 * its points and normals).
 */
export type StoredSkull = {
  bones: Record<string, [number, number, number]>
  points: number[]
  normals: number[]
  zone: number[]
  triangles: number[]
  bald: number[]
  baldNormals: number[]
}

export const POINT_UNIT = 1e-4
export const NORMAL_UNIT = 1e-3
export const ZONE_UNIT = 1e-2

const scaled = (values: number[], unit: number) =>
  Float32Array.from(values, (value) => value * unit)

const readSkull = (stored: StoredSkull): SkullData => ({
  bones: stored.bones,
  points: scaled(stored.points, POINT_UNIT),
  normals: scaled(stored.normals, NORMAL_UNIT),
  zone: scaled(stored.zone, ZONE_UNIT),
  triangles: Uint32Array.from(stored.triangles),
  bald: scaled(stored.bald, POINT_UNIT),
  baldNormals: scaled(stored.baldNormals, NORMAL_UNIT),
})

/** Flags (1 or 0 each) packed eight to a byte, first in the lowest bit, as base64. */
export function packFlags(flags: ArrayLike<number>): string {
  const bytes = new Uint8Array(Math.ceil(flags.length / 8))
  for (let i = 0; i < flags.length; i++) if (flags[i]) bytes[i >> 3]! |= 1 << (i & 7)
  let text = ''
  for (const byte of bytes) text += String.fromCharCode(byte)
  return btoa(text)
}

/** Flags packed by `packFlags` (a whole number of bytes' worth: the last few may be spare). */
export function unpackFlags(packed: string): Uint8Array {
  const text = atob(packed)
  const flags = new Uint8Array(text.length * 8)
  for (let i = 0; i < flags.length; i++) flags[i] = (text.charCodeAt(i >> 3) >> (i & 7)) & 1
  return flags
}

/**
 * The hairstyles to choose from — every avatar's hair, once each — the
 * skull they are carried over by; for each head that has hair cards
 * (named by its material), which of its points are its hair's shell (1)
 * rather than skin; and for every head, which of its triangles are its own
 * hair (1), taken out for a bald head (see bald-head.ts). Generated by
 * scripts/characters/gen-hair-styles.ts.
 */
const HAIR_STYLES_URL = '/characters/rocketbox/hair-styles.json'

export type StoredHairLibrary = {
  styles: HairStyleEntry[]
  skull: StoredSkull
  shells: Record<string, string>
  bald: Record<string, string>
}

export type HairLibrary = {
  styles: HairStyleEntry[]
  skull: SkullData
  shells: ReadonlyMap<string, Uint8Array>
  bald: ReadonlyMap<string, Uint8Array>
}

const unpackAll = (packed: Record<string, string>) =>
  new Map(Object.entries(packed).map(([head, flags]) => [head, unpackFlags(flags)]))

let library: Promise<HairLibrary> | null = null

export function loadHairLibrary(): Promise<HairLibrary> {
  library ??= fetch(HAIR_STYLES_URL)
    .then((response) => {
      if (!response.ok) throw new Error(`hair styles: ${response.status}`)
      return response.json() as Promise<StoredHairLibrary>
    })
    .then((file) => ({
      styles: file.styles.filter((style) => AVATAR_IDS.has(style.id)),
      skull: readSkull(file.skull),
      shells: unpackAll(file.shells),
      bald: unpackAll(file.bald),
    }))
    .catch((error: unknown) => {
      // A failed download can be tried again later.
      library = null
      throw error
    })
  return library
}

export function loadHairStyles(): Promise<HairStyleEntry[]> {
  return loadHairLibrary().then((loaded) => loaded.styles)
}
