import { ALL_AVATARS, type AvatarGender } from './avatar-catalog'

/**
 * A hairstyle: null keeps the character's own; BALD takes its hair off
 * (its hair cards hidden, its painted hair shaved to scalp); any other is
 * the id of the avatar whose hair it wears.
 */
export type HairStyle = string | null

export const BALD = 'bald'

const AVATAR_IDS = new Set(ALL_AVATARS.map((avatar) => avatar.id))

/** A hairstyle as saved or received: the character's own for anything unknown. */
export function readHairStyle(value: unknown): HairStyle {
  if (value === BALD) return BALD
  return typeof value === 'string' && AVATAR_IDS.has(value) ? value : null
}

/** A hairstyle the library offers: the avatar whose hair it is, and how that hair reads. */
export type HairStyleEntry = {
  id: string
  gender: AvatarGender
  length: 'short' | 'medium' | 'long'
}

/**
 * The bald skull every head shares (Rocketbox heads are one template per
 * sex), which hairstyles are carried over by: its points and their normals
 * (bind pose, m), each point's share of hair (0 on the face and ears, 1
 * where nearly every character's hair volume stands out of the skull), and
 * the face bones it is fitted to a character by.
 */
export type SkullData = {
  bones: Record<string, [number, number, number]>
  points: Float32Array
  normals: Float32Array
  zone: Float32Array
}

/**
 * The skull as the file stores it, in whole numbers: points in POINT_UNIT,
 * normals in NORMAL_UNIT, zone shares in ZONE_UNIT.
 */
export type StoredSkull = {
  bones: Record<string, [number, number, number]>
  points: number[]
  normals: number[]
  zone: number[]
}

export const POINT_UNIT = 1e-4
export const NORMAL_UNIT = 1e-3
export const ZONE_UNIT = 1e-2

const scaled = (values: number[], unit: number) =>
  Float32Array.from(values, (value) => value * unit)

const readSkull = (stored: StoredSkull): SkullData => ({
  bones: stored.bones,
  points: scaled(stored.points, POINT_UNIT),
  normals: scaled(stored.normals, NORMAL_UNIT),
  zone: scaled(stored.zone, ZONE_UNIT),
})

/** Flags (1 or 0 each) packed eight to a byte, first in the lowest bit, as base64. */
export function packFlags(flags: ArrayLike<number>): string {
  const bytes = new Uint8Array(Math.ceil(flags.length / 8))
  for (let i = 0; i < flags.length; i++) if (flags[i]) bytes[i >> 3]! |= 1 << (i & 7)
  let text = ''
  for (const byte of bytes) text += String.fromCharCode(byte)
  return btoa(text)
}

/** Flags packed by `packFlags` (a whole number of bytes' worth: the last few may be spare). */
export function unpackFlags(packed: string): Uint8Array {
  const text = atob(packed)
  const flags = new Uint8Array(text.length * 8)
  for (let i = 0; i < flags.length; i++) flags[i] = (text.charCodeAt(i >> 3) >> (i & 7)) & 1
  return flags
}

/**
 * The hairstyles to choose from — every avatar's hair, once each — the
 * skull they are carried over by, and, for each head that has hair cards
 * (named by its material), which of its points are its hair's shell (1)
 * rather than skin. Generated by scripts/characters/gen-hair-styles.ts.
 */
const HAIR_STYLES_URL = '/characters/rocketbox/hair-styles.json'

export type StoredHairLibrary = {
  styles: HairStyleEntry[]
  skull: StoredSkull
  shells: Record<string, string>
}

export type HairLibrary = {
  styles: HairStyleEntry[]
  skull: SkullData
  shells: ReadonlyMap<string, Uint8Array>
}

let library: Promise<HairLibrary> | null = null

export function loadHairLibrary(): Promise<HairLibrary> {
  library ??= fetch(HAIR_STYLES_URL)
    .then((response) => {
      if (!response.ok) throw new Error(`hair styles: ${response.status}`)
      return response.json() as Promise<StoredHairLibrary>
    })
    .then((file) => ({
      styles: file.styles.filter((style) => AVATAR_IDS.has(style.id)),
      skull: readSkull(file.skull),
      shells: new Map(
        Object.entries(file.shells).map(([head, packed]) => [head, unpackFlags(packed)]),
      ),
    }))
    .catch((error: unknown) => {
      // A failed download can be tried again later.
      library = null
      throw error
    })
  return library
}

export function loadHairStyles(): Promise<HairStyleEntry[]> {
  return loadHairLibrary().then((loaded) => loaded.styles)
}
